/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal local setup.
// It is committed here so the scaffold has complete TypeScript references from the start.
