insert into public.daily_light_entries (
  slug, title, summary, access_level, status, volume, volume_title, day, theme,
  old_testament_reading, new_testament_reading, key_verse_reference, key_verse_text,
  scripture_reference, scripture_text, reflection, prayer, reflection_question,
  today_practice, closing_thought, published_on
)
values
(
  'day-311-pour-out-your-heart',
  'Pour Out Your Heart',
  'Prayer Through Lament',
  'public',
  'published',
  'Volume Eleven',
  'The Heart of Prayer',
  311,
  'Prayer Through Lament',
  'Psalm 42:1–11',
  'John 11:28–36',
  'Psalm 62:8',
  'Trust in him at all times; ye people, pour out your heart before him: God is a refuge for us.',
  null,
  null,
  $daily311$Prayer does not require us to hide sorrow. Lament is the prayer of a heart that is hurting but still turning toward God. The wounded heart may speak honestly of grief, anger, confusion, and fear while continuing to remember the faithfulness of God.$daily311$,
  $prayer311$Heavenly Father, I bring You the sorrow, anger, fear, and confusion within me. Help me speak honestly without turning away from You. Receive my tears and questions, and become my refuge in the middle of pain. Remind me of Your faithfulness when hope feels weak, and hold me close through Jesus Christ. In His holy name, Amen.$prayer311$,
  'What sorrow or difficult emotion have I been afraid to express honestly before God?',
  'Write a brief prayer of lament. Name what hurts, ask what you need to ask, and end by naming one truth about God that remains unchanged.',
  'Lament is not faith abandoning God; it is the wounded heart refusing to stop speaking to Him.',
  date '2027-05-07'
),
(
  'day-312-standing-in-the-gap',
  'Standing in the Gap',
  'Interceding for Others',
  'public',
  'published',
  'Volume Eleven',
  'The Heart of Prayer',
  312,
  'Interceding for Others',
  'Exodus 32:7–14, 30–32',
  'Colossians 1:3–12',
  'Ezekiel 22:30',
  'I sought for a man among them, that should make up the hedge, and stand in the gap before me.',
  null,
  null,
  $daily312$Prayer is not only where we bring our own needs but where we carry the needs of others. Intercession is one of the quietest forms of service, faithfully bringing names and burdens before God with compassion and humility.$daily312$,
  $prayer312$Heavenly Father, Teach me to intercede faithfully for others. Bring to mind those who are suffering, weary, confused, or far from You. Help me pray with compassion, perseverance, and humility. Where I cannot change circumstances, let me faithfully carry names and needs before Your throne. In the name of Jesus Christ, Amen.$prayer312$,
  'Whose name has God been placing upon my heart in prayer?',
  'Choose one person and pray specifically for their spiritual, emotional, physical, and practical needs. Continue remembering them throughout the week.',
  'Intercession is love carrying another person’s name into the presence of God.',
  date '2027-05-08'
)
on conflict (day) do update set
  slug = excluded.slug,
  title = excluded.title,
  summary = excluded.summary,
  access_level = excluded.access_level,
  status = excluded.status,
  volume = excluded.volume,
  volume_title = excluded.volume_title,
  theme = excluded.theme,
  old_testament_reading = excluded.old_testament_reading,
  new_testament_reading = excluded.new_testament_reading,
  key_verse_reference = excluded.key_verse_reference,
  key_verse_text = excluded.key_verse_text,
  scripture_reference = excluded.scripture_reference,
  scripture_text = excluded.scripture_text,
  reflection = excluded.reflection,
  prayer = excluded.prayer,
  reflection_question = excluded.reflection_question,
  today_practice = excluded.today_practice,
  closing_thought = excluded.closing_thought,
  published_on = excluded.published_on;